module  -- shake: keep-all --deprecated_module: ignore

public import MeanFourier.AlmostConvergent
public import MeanFourier.AlmostPeriod.L2
public import MeanFourier.AlmostPeriod.Uniform
public import MeanFourier.BohrSet.Defs
public import MeanFourier.BohrSet.Doubling
public import MeanFourier.BohrSet.Regular
public import MeanFourier.InvtMean.Defs
public import MeanFourier.InvtMean.Foelner
public import MeanFourier.InvtMean.Riemann
public import MeanFourier.InvtMean.UAPExtension
public import MeanFourier.InvtMean.VonNeumann
public import MeanFourier.Mathlib.Algebra.BigOperators.GroupWithZero.Finset
public import MeanFourier.Mathlib.Algebra.Group.Action.Pointwise.Set.Basic
public import MeanFourier.Mathlib.Algebra.Group.Pointwise.Set.Basic
public import MeanFourier.Mathlib.Algebra.Module.Equiv.Basic
public import MeanFourier.Mathlib.Analysis.Convex.TotallyBounded
public import MeanFourier.Mathlib.Analysis.Normed.Group.Bounded
public import MeanFourier.Mathlib.Analysis.Normed.Group.Pointwise
public import MeanFourier.Mathlib.Analysis.Normed.Module.Ball.Pointwise
public import MeanFourier.Mathlib.Combinatorics.Additive.ApproximateSubgroup
public import MeanFourier.Mathlib.Combinatorics.Additive.CovBySMul
public import MeanFourier.Mathlib.Combinatorics.Additive.VCDim
public import MeanFourier.Mathlib.Combinatorics.SetFamily.HausslerPacking
public import MeanFourier.Mathlib.Combinatorics.SetFamily.VCDim
public import MeanFourier.Mathlib.Data.ENNReal.BigOperators
public import MeanFourier.Mathlib.Data.ENNReal.Operations
public import MeanFourier.Mathlib.Data.ENat.Basic
public import MeanFourier.Mathlib.Data.ENat.BigOperators
public import MeanFourier.Mathlib.Data.EReal.Basic
public import MeanFourier.Mathlib.Data.Finset.Pi
public import MeanFourier.Mathlib.Data.Fintype.BigOperators
public import MeanFourier.Mathlib.Data.Fintype.Pi
public import MeanFourier.Mathlib.Data.Real.ENatENNReal
public import MeanFourier.Mathlib.Data.Set.Basic
public import MeanFourier.Mathlib.Data.Set.Card
public import MeanFourier.Mathlib.Data.Set.Prod
public import MeanFourier.Mathlib.MeasureTheory.Group.FoelnerFilter
public import MeanFourier.Mathlib.MeasureTheory.Integral.Average
public import MeanFourier.Mathlib.Topology.Algebra.Module.Equiv
public import MeanFourier.Mathlib.Topology.Bornology.Basic
public import MeanFourier.Mathlib.Topology.MetricSpace.Cover
public import MeanFourier.Mathlib.Topology.MetricSpace.CoveringNumbers
public import MeanFourier.Mathlib.Topology.MetricSpace.MetricSeparated
public import MeanFourier.Mathlib.Topology.MetricSpace.Pseudo.Defs
public import MeanFourier.Translate
public import MeanFourier.UnitaryDual
public import MeanFourier.UnitaryRep
public import MeanFourier.UnitaryRepresentation
public import MeanFourier.VCDim.ArithmeticRegularity
public import MeanFourier.VCDim.Averaging
